### ISSUE TITLE
Crash when viewing item in jei

### ISSUE THREAD

**Issue by Zelda-Swordsman** [scalda/Monsterpack#1]
While in jei, I limited the search to just Thaumcraft to see all the new blocks in Thaumcraft 6. When I got to the fourth page (using gui scale auto) my game freezes, followed by a crash.
Crash report:
[crash-2018-02-08_20.25.11-client.txt](https://github.com/scalda/Monsterpack/files/1709430/crash-2018-02-08_20.25.11-client.txt)
EDIT: It seems to be whenever jei tries to render thaumcraft's foci. When I started typing focus, the same crash occured.

**Comment by KelleyEngineering** [comment]
Same thing for me. I'm attempting to recreate the issue in another modpack to see if it's a Thaumcraft conflict or a Monsterpack conflict (my money's on Thaumcraft)
Edit: This issue is Thaumcraft related, not Monsterpack related. Bug report submitted two days ago.
           https://github.com/Azanor/thaumcraft-beta/issues/237

**Comment by scalda** [comment]
i have just released a fix in 1.2 that makes a fix for the time being til the mod updates
