### ISSUE TITLE
Chicken Wing Ring cannot be crafted

### ISSUE THREAD

**Issue by KelleyEngineering** [scalda/Monsterpack#3]
Since the Animania mod removes all vanilla chickens from the game, the Chicken Wing ring cannot be crafted. Recommend adding a recipe that replaces vanilla chickens with Animania chickens for the Chicken Wing Ring.

**Comment by scalda** [comment]
no need to create custom recipe as i have enabled the vanilla chickens aswell in the next version of the pack
