### ISSUE TITLE
Animania Spawn Cap needs to be tweaked.

### ISSUE THREAD

**Issue by KelleyEngineering** [scalda/Monsterpack#4]
The Modpack will forcibly despawn Animania mobs as a spawn cap is reached regardless of whether they were bred in or named. 

Looking over the Animania Github, this issue was resolved by removed Spawn Caps altogether in v1.4.4. However the .cfg files still have a spawn cap and they're all set to "40" 

Recommend Increasing the spawn cap for Animania mobs to allow for Meat farming.

This is a fun pack Scalda, reminds me of SS3 and a more magic based Hermitpack. Keep up the great work.

**Comment by scalda** [comment]
i have made a new regen of the file for this to fix it in the next version
