### ISSUE TITLE
Mega Loot timeouts

### ISSUE THREAD

**Issue by KelleyEngineering** [scalda/Monsterpack#5]
Whenever a Loot Case from the Mega Loot mod generates a piece of armor, the user who picks up the piece immediately times out of the server. This has happened three times so far. No crash log is generated since it's just a simple time-out.

Once the player, logs back in, the Loot case has reappeared in their inventory as if it had never been opened before. If the user gets a Bauble, tool or weapon, the time-out does not occur. I understand that this mod is in extreme BETA so these types of things are expected.

I attempted to recreate this issue in Single Player and by LAN. The LAN connection was not a localhost. The time-out did not occur. As I am not a server admin in the community I'm a part of, I am unable to do further testing. I did notice that the textures for armor do not render properly in Monsterpack. They loaded just fine in a standalone build. 

Crash Report: None, the player is timed out and is able to immediately log back in with no issues. This may be related to armor textures that do not render properly in the pack. The armor rendered properly when I loaded it in a non-Monsterpack modpack
Modpack Version: 1.1
Mod Version: (Mega Loot) 0.0.12

**Comment by WinterGrave** [comment]
Pushed hotfix for the issue: https://minecraft.curseforge.com/projects/megaloot/files/2530661

**Comment by scalda** [comment]
thanks winter
