### ISSUE TITLE
Veinminer Tool Registry is incomplete.

### ISSUE THREAD

**Issue by KelleyEngineering** [scalda/Monsterpack#6]
While Veinminer's autodetector did a good job of finding blocks, it did not add the thaumcraft, inbetweenlands, botania, NewThings, or Mega Caseloot's tools to the registry. Also, the autodetector adds the wrong ItemID for Applied Energistics and Astral Sorecery tools. 

I made an updated tool list that includes all the tools from the above stated mods to save you time if you wanted to use it.
https://drive.google.com/open?id=1ZCLzyMjv081Cd2518RaNqghzJbmudFN3

**Comment by scalda** [comment]
Thanks for the help i have added this for the next major release of the pack
