### ISSUE TITLE
[suggestion] <3 

### ISSUE THREAD

**Issue by EmeraldCleaver77** [scalda/Monsterpack#7]
heyo !!
i would like to suggest u to add the mod "Dark Utilities" as i find this mod a very lovely mod that will fit in with the theme of the pack especially for the vector plates which have always proved very handy in mob farms. secondly for the Mob Filters it permit a certain type of mob to pass through, but block all others. There are eleven different kinds, each with a slightly different crafting recipe. The block texture indicates the type of Mob than can pass through.i think that this block will help us deal better with animinia mobs as they bread when they r in the mood and some kind of automation can really be helpful 
at last thank you for you amazing work and lov u all <3 <3 <3

**Comment by scalda** [comment]
this has now been added to the pack

**Comment by KelleyEngineering** [comment]
Yes! Thanks Scalda!

**Comment by EmeraldCleaver77** [comment]
thank u scalda-senpai
