### ISSUE TITLE
[Suggestion] More power Options

### ISSUE THREAD

**Issue by KelleyEngineering** [scalda/Monsterpack#8]
I love the Extra utilities generators, or even all the dynamos from thermal expansion, but they're difficult to maintain and keep fed for extended periods of time. If I wanted a fully automated ore processing station, I'd need to constantly be feeding lava or coal or some resource that isn't infinitely renewable into it. Never mind the fact that a decent ME system requires a constant feed of power. At the end of the day, players will be pigeonholed into using Ender IO's solar panels and forgoing any other power source for convenience sake. simply, the Power options in this pack are too few.

I recommend that "Simple Generators" by ValkyrieofNight be added to the pack. The 5 generators offered by the pack have a decent grind to get them to their max tier and they can be sustained on non-renewable resources for longer periods than Extra Utilities. The RFp/t generated makes them a superior option.

I was also reluctant to suggest it since it's considered by most to be "OP" but Iskallium Reactors by WinterGrave would also fit right in. The configs could make it so that less RF per tick is generated passively to appease the haters.

**Comment by Ranger1230** [comment]
I like Extreme Reactors (lots of power) and Deep Resonance (Decent power, cool animations). Though they have their own Ores, so with an existing world that would make it hard to get the Ores needed. Though with a mining world that might not be too bad.

**Comment by KelleyEngineering** [comment]
Ranger I understand what your saying but this pack is fun because it offers a different type of difficulty from other modpacks. 

Frankly speaking, and imho adding Extreme Reactors is too OP for what this modpack is trying to do. It’s part of the reason why I was hesitant to suggest iskallium reactors. 

What I was trying to suggest was more options for power generation to take advantage of limited resources the pack already has.

**Comment by scalda** [comment]
sadly i have spoke to stress regarding this and she said no to more power options sorry

**Comment by KelleyEngineering** [comment]
S’all good. So far we’ve found some creative albeit convoluted solutions to power anyway. Thanks for looking into it Scalda
