### ISSUE TITLE
iChisel turns stacks of items into single items

### ISSUE THREAD

**Issue by ShadowFox85** [scalda/Monsterpack#9]
Title basically says it all.

I was using the iChisel to chisel a load of factory blocks. Each stack of 64 blocks turned into a single item after chiselling them. I've tried with different blocks and the same thing happened. Also tried both the chisel and chisel all modes and the same thing happened.

Normal diamond chisel works fine.

**Comment by scalda** [comment]
Ok this is a bug with in the mod if we have the durability disabled then we get this issue, so i will turn the durability back on for the next version of the pack so this function can be used without losing blocks
